//adding event listeners
document.getElementById('rock').addEventListener('click', function() { playGame('rock'); });
document.getElementById('paper').addEventListener('click', function() { playGame('paper'); });
document.getElementById('scissors').addEventListener('click', function() { playGame('scissors'); });

//getting computer choice bt random selecting a number 1-3
function computerTurn(){

    const randNum = Math.floor(Math.random() * 3) + 1;

    switch(randNum){
        case 1:
            computer = "rock";
            break;
        case 2:
            computer = "paper";
            break;
        case 3:
            computer = "scissors";
            break;
    }
    return computer;
}


/*
* function for figuring out who won the game
*
*   takes in params userChoice and computerChoice
*
*
* */
function getWinner(userChoice, computerChoice) {
    //Tie
    if (userChoice === computerChoice) {
        return 'tie';
    }
    if ((userChoice === 'rock' && computerChoice === 'scissors') || (userChoice === 'paper' && computerChoice === 'rock') || (userChoice === 'scissors' && computerChoice === 'paper')
    ) {
        return 'win';
    }
}
//showing results to div
function displayResult(userChoice, computerChoice, outcome) {
    const resultDiv = document.getElementById('result');
    let result = `You chose ${userChoice}, Computer chose ${computerChoice}.`;
    if (outcome === 'tie') {
        result += " It's a tie!";
    } else if (outcome === 'win') {
        result += " You win!";
    } else {
        result += " You lose!";
    }
    // making content of the div show the result
    resultDiv.textContent = result;
}
//playGame function
//     takes in the users choice, calls computerTurn function to gather the response
//     then an outcome is generated by calling the getWinner function
function playGame(userChoice) {
    const computerChoice = computerTurn();
    const outcome = getWinner(userChoice, computerChoice);
    displayResult(userChoice, computerChoice, outcome);
}